sudo: false

language: go
env:
  - GO111MODULE=on
go:
  - 1.12.x
git:
  depth: 1

install: true

notifications:
  email: false

script:
  - golangci-lint run       # run a bunch of code checkers/linters in parallel
  - go test -v -race ./...  # Run all t
